config/routes.rb
Rails.application.routes.draw do
  resources :missions

  root 'missions#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mission.rb
class Mission < ApplicationRecord
  # belongs_to :user
  
  enum priority:{ important: 0, normal: 1 }
  enum status:{ pending: 0, approved: 1, rejected: 2, canceled: 3 }

  validates :name, format: { with: /\A[A-Z0-9]+\z/, message: :uppercaseonly }, presence: true
  validates :description, presence: true
  # validates_datetime :complete_time, :after => :start_time 
  scope :order_by_complete_time, -> { order(complete_time: :asc) }

  include AASM

  aasm column: :status do
    state :pending, initial: true
    state :approved, :rejected, :canceled

    event :approve do
      transitions from: :pending, to: :approved
    end

    event :reject do
      transitions from: :pending, to: :rejected
    end

    event :cancel do
      transitions from: :rejected, to: :canceled
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # has_many :missions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    # 可以將 ["en", "zh-TW"] 設定為 VALID_LANG 放到 config/environment.rb 中
    if params[:locale] && I18n.available_locales.include?( params[:locale].to_sym )
      session[:locale] = params[:locale]
    end
  
    I18n.locale = session[:locale] || I18n.default_locale
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :find_mission, only: [:edit, :update, :destroy]
  before_action :find_mission_ransack, only: [:index]

  def index
    @missions = @q.result.order_by_complete_time
  end

  def new
    @mission = Mission.new
  end

  def create
    @mission = Mission.new(mission_params)
    if @mission.save
      redirect_to root_path, notice: t(".notice")
    else 
      render :new
    end
  end

  def edit
  end

  def update
    if @mission.update(mission_params)
      redirect_to root_path, notice: t(".notice")
    else 
      render :edit
    end
  end

  def destroy
    @mission.destroy if @mission
    redirect_to root_path, notice: t(".notice")
  end

  private
  def mission_params
    params.require(:mission).permit(:name, :priority, :status, :start_time, :complete_time, :description)
  end

  def find_mission
    @mission = Mission.find(params[:id])
  end

  def find_mission_ransack
    @q = Mission.ransack(params[:q])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def restricted_statuses
    statuses.except :rejected, :canceled
  end

end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EighteenMen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <div class="container">
    <%= yield %>
    </div>
    
  </body>
</html>

app/views/missions/_form.html.erb
<% if @mission.errors.present? %>
  <ul>
    <% @mission.errors.each do |error, message| %>
      <li>
        <%= t("#{error} ") + t('missions.validate.error') + " #{message}" %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= simple_form_for(mission) do |m| %>
  <div class="form-group">
    <%#= m.label :name, t('form.name') %>
    <%#= m.text_field :name  %>
    <%= m.input :name, error: '', hint: t("missions.hint") %>
  </div>

  <div class="form-group">
    <%= m.input :priority %>
  </div>
  
  <div class="form-group">
    <%= m.input :status %>
  </div>
  
  <div class="form-group">
    <%= m.input :start_time, as: :date, html5: true %>
  </div>
  
  <div class="form-group">
    <%= m.input :complete_time, as: :date, html5: true %>
  </div>

  <div class="form-group">
    <%= m.input :description, placeholder: t("missions.placeholder") %>
  </div>

  <div class="form-group">
    <%= m.submit t("Confirm") %>
  </div>
  
<% end %>

app/views/missions/edit.html.erb
<h1><%= t("mission.edit") %></h1>

<%= render "form", mission: @mission %>

<%= link_to t("back_to_mission_list"), root_path %>

app/views/missions/index.html.erb
<h1><%= t("mission.list")%></h1>

<%= link_to t("mission.new"), new_mission_path, class:"btn btn-sm btn-success" %>

<%= search_form_for @q do |f| %>
  <%= f.label :name, t('mission.name') %>
  <%= f.search_field :name_cont, placeholder: "write something" %>

  <%= f.label :status, t('mission.status') %>
  <%= f.select :status_eq,
      Mission.statuses.map { |status| [t("enums.status.#{status[0]}"), status[1]] } %>

  <%= f.submit %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <td><%= t("mission.name") %> </td>
      <td><%= sort_link(@q, :priority, t("mission.priority")) %></td>
      <td><%= sort_link(@q, :status, t("mission.status")) %></td>
      <td><%= sort_link(@q, :start_time, t("mission.start_time")) %></td>
      <td><%= sort_link(@q, :complete_time, t("mission.complete_time")) %></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @missions.each do |mission| %>
    <tr>
      <td> <%= mission.name %></td>
      <td> <%= t("enums.status.#{mission.priority}") %></td>
      <td> <%= t("enums.status.#{mission.status}")  %></td>
      <td> <%= mission.start_time %></td>
      <td> <%= mission.complete_time %></td>
      <td>
        <%= link_to t("button.edit"), edit_mission_path(mission), class:"btn btn-lx btn-warning"%>
        <%= link_to t("button.delete"), mission_path(mission), method: "delete", data: { confirm: "are you sure?"} %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "中文版", :controller => controller_name, :action => action_name, :locale => "zh-TW" %>
<%= link_to "English", :controller => controller_name, :action => action_name, :locale => "en" %>

app/views/missions/new.html.erb
<h1><%= t("mission.new") %></h1>

<%= render "form", mission: @mission %>

<%= link_to t("back_to_mission_list"), root_path %>